apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  replicas: 1
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account-service
          image: account-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
#          volumeMounts:
#            - name: config
#              mountPath: /app/xconfig
          ports:
            - containerPort: 8022
#      initContainers:
#        - name: git-clone
#          image: alpine/git:1.0.4
#          command: ['/bin/sh', '-c']
#          args: ['git clone --branch master https://github.com/makcalif/config-properties.git && mv config-properties/account-service/dev/* /app/config'] # 3
#          volumeMounts:
#            - name: config
#              mountPath: /app/xconfig
      volumes:
        - name: config
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 8022  # from config map
  type: ClusterIP
  selector:
    app: account

---
apiVersion: v1
kind: Service
metadata:
  name: account-service-front
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 8022   # from config map
  selector:
    app: account
