apiVersion: v1
kind: Service
metadata:
  name: account-service-front
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 8022   # from config map
  selector:
    app: account
