kind: Service
apiVersion: v1
metadata:
  name: account-service
spec:
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 8022  # from config map
  type: NodePort
  selector:
    app: account
